# Generated by Django 5.1.6 on 2025-02-07 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='subscribers'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participaters',
            field=models.ManyToManyField(blank=True, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='participaters'),
        ),
    ]
